title: Dreaming in digital…
author:
  name: "Dmitriy Safronov"
  email: "zimniy@cyberbrain.pw"
description: Здесь, наверное, нужно написать что-нибудь мотивирующее и и глубокомысленное, но мне лень.

# theme: minima
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

header_pages:
  - about.md

show_excerpts: true

minima:
  skin: auto
  date_format: "%Y %b %-d"
  social_links:
    - platform: github
      user_url: "https://github.com/DmitriySafronov"
    - platform: gitlab
      user_url: "https://gitlab.com/zimniy"
      
#

google_analytics: G-VWE7QJCSVH

#

disqus:
  shortname: cyberbrain-pw

#

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      comments: true
  -
    scope:
      path:            "assets/**/*"
    values:
      sitemap:         false

# 

# sass:
#   style: expanded
